"""Step 5: LAMOST x Gaia cross-match (1 arcsec) + schema & QC reports.

Inputs
------
- data/processed/hivel_gaia_kinematics.parquet  (1101 rows from Step 4B)
- data/external/lamost/*                        (any DR9 LRS gz CSV)

Outputs
-------
- data/processed/hivel_gaia_lamost_master.parquet
- data/processed/hivel_gaia_lamost_master.csv
- data/processed/hivel_gaia_lamost_matched.csv     (long-format multi-epoch)
- reports/lamost_catalog_schema.md
- reports/lamost_crossmatch_summary.md
"""
from __future__ import annotations
import sys
from pathlib import Path
import numpy as np
import pandas as pd
from astropy.coordinates import SkyCoord
import astropy.units as u

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from caosp_hivel.paths import ensure_dirs, EXTERNAL_DIR, PROCESSED_DIR
from caosp_hivel.lamost import discover_files, schema, load_full, COLUMN_ALIASES
from caosp_hivel.config import settings
from caosp_hivel.log import get_logger

REPORTS_DIR = ROOT / "reports"
RADIUS_ARCSEC = float(settings()["crossmatch"]["radius_arcsec"])

# canonical columns we want from the stellar parameter catalog
STELLAR_COLS = (
    "obsid", "designation", "gaia_source_id", "ra", "dec",
    "snru", "snrg", "snrr", "snri", "snrz",
    "class", "subclass",
    "teff", "teff_err", "logg", "logg_err", "feh", "feh_err",
    "rv", "rv_err", "alpha_m", "alpha_m_err",
)


def _classify_files(paths: list[Path]) -> tuple[Path | None, Path | None, list[dict]]:
    """Return (stellar_path, general_path, [schema dicts]).

    Stellar = any file whose schema contains both 'rv' and 'teff' canonicals.
    General = any other file with 'gaia_source_id' + ra/dec.
    """
    schemas = [schema(p) for p in paths]
    stellar = next(
        (s["path"] for s in schemas if {"rv", "teff", "logg", "feh"} <= s["canonical"].keys()),
        None,
    )
    general = next(
        (s["path"] for s in schemas
         if s["path"] != stellar and {"gaia_source_id", "ra", "dec"} <= s["canonical"].keys()),
        None,
    )
    return stellar, general, schemas


def _write_schema_report(schemas: list[dict], stellar: Path | None, general: Path | None) -> Path:
    md = ["# LAMOST catalog schema report\n",
          "Generated by `scripts/05_lamost_crossmatch.py`.\n"]
    md.append("## Files discovered\n")
    md.append("| file | size (MB) | n columns | role |")
    md.append("|---|---:|---:|---|")
    for s in schemas:
        role = "stellar" if s["path"] == stellar else ("general" if s["path"] == general else "other")
        md.append(f"| `{s['path'].name}` | {s['size_mb']:.0f} | {s['n_columns']} | {role} |")
    md.append("")

    md.append("## Canonical-field detection\n")
    md.append("| canonical | aliases tried | " + " | ".join(s["path"].name for s in schemas) + " |")
    md.append("|---|---|" + "|".join("---" for _ in schemas) + "|")
    for canon, aliases in COLUMN_ALIASES.items():
        cells = [s["canonical"].get(canon, "—") for s in schemas]
        md.append(f"| `{canon}` | {', '.join(aliases)} | " + " | ".join(cells) + " |")
    md.append("")

    md.append("## Full headers\n")
    for s in schemas:
        md.append(f"### `{s['path'].name}` ({s['n_columns']} columns)")
        md.append("```")
        md.append(", ".join(s["header"]))
        md.append("```\n")

    out = REPORTS_DIR / "lamost_catalog_schema.md"
    out.write_text("\n".join(md), encoding="utf-8")
    return out


def _best_match(group: pd.DataFrame) -> pd.Series:
    """Pick best LAMOST match: highest snrg, then lowest rv_err, then closest sep."""
    g = group.copy()
    g["_snrg"] = g["snrg"].fillna(-np.inf)
    g["_rverr"] = g["rv_err"].fillna(np.inf)
    g = g.sort_values(["_snrg", "_rverr", "sep_arcsec"], ascending=[False, True, True])
    return g.iloc[0]


def main() -> int:
    ensure_dirs()
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    log = get_logger("caosp.step5")

    files = discover_files(EXTERNAL_DIR / "lamost")
    if not files:
        log.error("no LAMOST file in %s", EXTERNAL_DIR / "lamost")
        return 1

    stellar, general, schemas = _classify_files(files)
    schema_md = _write_schema_report(schemas, stellar, general)
    log.info("schema -> %s", schema_md)

    if stellar is None:
        log.error("no stellar-parameter catalog found (need rv/teff/logg/feh)")
        return 1
    log.info("using stellar catalog: %s", stellar.name)

    # ---- load Gaia kinematics ----
    gaia_path = PROCESSED_DIR / "hivel_gaia_kinematics.parquet"
    if not gaia_path.exists():
        log.error("missing %s — run step 4B first", gaia_path)
        return 1
    gaia = pd.read_parquet(gaia_path)
    log.info("Gaia kinematics: %d rows", len(gaia))

    # ---- load LAMOST stellar (~10M rows) ----
    lamost = load_full(stellar, columns=STELLAR_COLS)
    log.info("LAMOST stellar: %d rows after sentinel cleanup", len(lamost))

    # drop LAMOST rows with no usable RA/Dec
    lamost = lamost.dropna(subset=["ra", "dec"]).reset_index(drop=True)

    # ---- SkyCoord cross-match (1 arcsec, all neighbours) ----
    log.info("building SkyCoords ...")
    cg = SkyCoord(gaia["ra"].values * u.deg, gaia["dec"].values * u.deg, frame="icrs")
    cl = SkyCoord(lamost["ra"].values * u.deg, lamost["dec"].values * u.deg, frame="icrs")
    log.info("search_around_sky r=%.2f arcsec ...", RADIUS_ARCSEC)
    # cg.search_around_sky(cl, r) returns (idx_into_cl, idx_into_cg, sep2d, sep3d)
    idx_l, idx_g, sep, _ = cg.search_around_sky(cl, RADIUS_ARCSEC * u.arcsec)
    log.info("%d Gaia-LAMOST pair(s) within %.2f arcsec", len(idx_g), RADIUS_ARCSEC)

    if len(idx_g) == 0:
        log.warning("no matches found")
        long = pd.DataFrame()
    else:
        long = lamost.iloc[idx_l].reset_index(drop=True)
        long["gaia_idx"] = idx_g
        long["sep_arcsec"] = sep.arcsec
        long["gaia_source_id_query"] = gaia["source_id"].iloc[idx_g].values
        # sanity: LAMOST already records gaia_source_id; flag agreement
        long["lamost_gaia_match"] = (
            pd.to_numeric(long["gaia_source_id"], errors="coerce").astype("Int64")
            == long["gaia_source_id_query"].astype("int64")
        )

    # ---- best-match per Gaia source ----
    long_path = PROCESSED_DIR / "hivel_gaia_lamost_matched.csv"
    if not long.empty:
        long.to_csv(long_path, index=False)
    else:
        pd.DataFrame().to_csv(long_path, index=False)

    if not long.empty:
        # groupby.apply returns one row per group, indexed by group key (gaia_idx)
        best = long.groupby("gaia_idx", group_keys=True).apply(_best_match, include_groups=False)
        n_per = long.groupby("gaia_idx").size().rename("lamost_n_matches")
        best["lamost_n_matches"] = n_per
        # best is now indexed by gaia_idx (positional index into the gaia DataFrame)
    else:
        best = pd.DataFrame()

    # ---- assemble master ----
    master = gaia.copy().reset_index(drop=True)
    rename_map = {
        "obsid": "lamost_obsid",
        "designation": "lamost_designation",
        "gaia_source_id": "lamost_gaia_source_id",
        "ra": "lamost_ra",
        "dec": "lamost_dec",
        "snrg": "lamost_snrg", "snrr": "lamost_snrr",
        "snri": "lamost_snri", "snrz": "lamost_snrz", "snru": "lamost_snru",
        "class": "lamost_class", "subclass": "lamost_subclass",
        "teff": "lamost_teff", "teff_err": "lamost_teff_err",
        "logg": "lamost_logg", "logg_err": "lamost_logg_err",
        "feh": "lamost_feh", "feh_err": "lamost_feh_err",
        "rv": "lamost_rv", "rv_err": "lamost_rv_err",
        "alpha_m": "lamost_alpha_m", "alpha_m_err": "lamost_alpha_m_err",
        "sep_arcsec": "lamost_best_sep_arcsec",
        "lamost_n_matches": "lamost_n_matches",
    }
    if not best.empty:
        keep = [c for c in rename_map if c in best.columns]
        chunk = best[keep].rename(columns=rename_map)
        # align by gaia row position
        master = master.join(chunk, how="left")
        # convenience: lamost_best_snr (use snrg as the canonical SNR proxy)
        master["lamost_best_snr"] = master.get("lamost_snrg")
    else:
        for v in rename_map.values():
            master[v] = pd.NA
        master["lamost_best_snr"] = pd.NA

    master["has_lamost"] = master["lamost_obsid"].notna()
    master["delta_rv"] = master["lamost_rv"] - master["radial_velocity"]

    out_parquet = PROCESSED_DIR / "hivel_gaia_lamost_master.parquet"
    out_csv = PROCESSED_DIR / "hivel_gaia_lamost_master.csv"
    master.to_parquet(out_parquet, index=False)
    master.to_csv(out_csv, index=False)
    log.info("master -> %s + .csv", out_parquet)

    # ---- report ----
    n_master = len(master)
    n_lam = int(master["has_lamost"].sum())
    n_qall = int(master["q_all"].sum())
    n_qall_lam = int((master["q_all"] & master["has_lamost"]).sum())
    seps = master.loc[master["has_lamost"], "lamost_best_sep_arcsec"].dropna()
    drv = master.loc[master["has_lamost"] & master["radial_velocity"].notna(), "delta_rv"].dropna()

    md = []
    md.append("# Gaia × LAMOST cross-match summary (Step 5)\n")
    md.append(f"Generated by `scripts/05_lamost_crossmatch.py`. Radius = {RADIUS_ARCSEC} arcsec.\n")

    md.append("## 1. LAMOST file used\n")
    md.append(f"- Stellar catalog: `{stellar.name}` ({stellar.stat().st_size/1e6:.0f} MB, "
              f"{len(lamost)} rows after sentinel cleanup)")
    if general:
        md.append(f"- General catalog (not used for cross-match): `{general.name}`")
    md.append("")

    md.append("## 2. Match counts\n")
    md.append("| metric | value |")
    md.append("|---|---:|")
    md.append(f"| Gaia master rows | {n_master} |")
    md.append(f"| Matched to LAMOST (any) | {n_lam} ({100*n_lam/n_master:.1f}%) |")
    md.append(f"| q_all (Gaia clean) | {n_qall} |")
    md.append(f"| q_all matched to LAMOST | {n_qall_lam} ({100*n_qall_lam/max(n_qall,1):.1f}%) |")
    md.append(f"| Pairs within {RADIUS_ARCSEC} arcsec (multi-epoch incl.) | {len(long)} |")
    md.append("")

    md.append("## 3. Per-source-catalog matches\n")
    md.append("| source catalog | rows in master | matched to LAMOST | %% |")
    md.append("|---|---:|---:|---:|")
    for label in ("li2021", "li2023", "liao2024"):
        sel = master["catalogs"].fillna("").str.contains(label)
        a = int(sel.sum())
        b = int((sel & master["has_lamost"]).sum())
        md.append(f"| {label} | {a} | {b} | {100*b/max(a,1):.1f}% |")
    md.append("")

    if len(seps):
        md.append("## 4. Match angular separation\n")
        q = seps.quantile([0, .5, .9, .99, 1.0]).round(3).to_dict()
        md.append("| stat | sep (arcsec) |")
        md.append("|---|---:|")
        for p, v in q.items():
            label = {0: "min", 0.5: "median", 0.9: "p90", 0.99: "p99", 1.0: "max"}[p]
            md.append(f"| {label} | {v} |")
        md.append("")

    if len(drv):
        med = float(drv.median())
        mad = float((drv - med).abs().median())
        n_outlier = int((drv.abs() > 50).sum())
        md.append("## 5. RV consistency: lamost_rv − Gaia RV\n")
        md.append(f"- common-sample size: {len(drv)}")
        md.append(f"- median Δrv: **{med:.2f} km/s**")
        md.append(f"- MAD: **{mad:.2f} km/s**")
        md.append(f"- p90 |Δrv|: **{drv.abs().quantile(0.9):.2f} km/s**")
        md.append(f"- p99 |Δrv|: **{drv.abs().quantile(0.99):.2f} km/s**")
        md.append(f"- |Δrv| > 50 km/s outliers: **{n_outlier}**")
        md.append("")

    md.append("## 6. LAMOST physical-parameter completeness (matched subset)\n")
    matched = master[master["has_lamost"]]
    md.append("| field | NaN | %% |")
    md.append("|---|---:|---:|")
    for c in ("lamost_teff", "lamost_logg", "lamost_feh", "lamost_snrg",
              "lamost_rv", "lamost_rv_err"):
        m = int(matched[c].isna().sum()) if c in matched.columns else len(matched)
        md.append(f"| {c} | {m} | {100*m/max(len(matched),1):.1f}% |")
    md.append("")

    # top candidates that got LAMOST coverage
    top_path = PROCESSED_DIR / "top_unbound_candidates.csv"
    if top_path.exists():
        top = pd.read_csv(top_path)
        joined = top.merge(
            master[["source_id", "has_lamost", "lamost_obsid",
                    "lamost_rv", "lamost_teff", "lamost_logg", "lamost_feh"]],
            on="source_id", how="left",
        )
        n_top_lam = int(joined["has_lamost"].fillna(False).sum())
        md.append("## 7. Top-50 unbound candidates with LAMOST\n")
        md.append(f"- top file: `{top_path.relative_to(ROOT)}`")
        md.append(f"- with LAMOST match: **{n_top_lam} / {len(top)}**\n")

    md.append("## 8. Caveats\n")
    md.append("- LAMOST RV and Gaia RV are measured at different epochs; binaries and pulsators "
              "will show large Δrv. Treat |Δrv| > 50 km/s as a flag for follow-up, not a rejection.")
    md.append("- LAMOST SNR (we use snrg) is a continuum SNR; very low SNR matches with implausible "
              "stellar params should be down-weighted in any ML candidate ranking.")
    md.append("- Multi-epoch matches are kept in `hivel_gaia_lamost_matched.csv`. The master table "
              "carries only the best epoch per Gaia source, plus `lamost_n_matches`.\n")

    out = REPORTS_DIR / "lamost_crossmatch_summary.md"
    out.write_text("\n".join(md), encoding="utf-8")
    log.info("summary -> %s", out)

    print(f"\nLAMOST: {n_lam}/{n_master} matched, q_all+LAMOST = {n_qall_lam}/{n_qall}")
    if len(drv):
        print(f"  delta_rv (lamost - gaia): median={float(drv.median()):.2f} km/s, "
              f"|delta_rv|>50: {int((drv.abs()>50).sum())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
